### ISSUE TITLE
有指南针等功能的校准组件么

### ISSUE THREAD

**Issue by Swordce** [dji-sdk/Mobile-UXSDK-Android#132]

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/51628'>Zendesk ticket #51628</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/51628'>Zendesk ticket #51628</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
在PreFlightStatusWidget下的PreFlightCheckListPanel有指南针校准功能，没有其他独立的组件。
https://developer.dji.com/api-reference/android-uilib-api/Widgets/PreFlightCheckListPanel.html#preflightchecklistpanel

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>

**Comment by Swordce** [comment]
点击校准后，preflightchecklistpanel直接变空白了，并没有校准功能出来

**Comment by Swordce** [comment]
点击校准后，只是PreFlightCheckListPanel被隐藏了，其他的就没反应了

**Comment by Swordce** [comment]
点击校准后，校准的弹框无法正常显示出来，用demo倒是可以，请问是什么问题

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/51628'>Zendesk ticket #51628</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
可以对比参考下官方示例的layout。
https://github.com/dji-sdk/Mobile-UXSDK-Android

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
