### ISSUE TITLE
No Video in FPVWidget

### ISSUE THREAD

**Issue by idcc-cursor** [dji-sdk/Mobile-UXSDK-Android#138]
Hello I try Mobile-UXSDK-Android TAG v4.16 , 
Setup: A3 + Lightbridge2 with Z30 Camera and CrystalSky
I am not able to get a Video in FPVWidget. 
With DJI Pilot I am able to see the FPV Video from Z30 with SDK there is no Video

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/60654'>Zendesk ticket #60654</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
A3 + LB2 with Z30 requires some initialise settings to make the video works.
1. You need to set the bandwidth allocation through LightBridgeLink class, setBandwidthAllocationForLBVideoInputPort depends on your settings.
Link：https://developer.dji.com/api-reference/android-api/Components/LBAirLink/DJILBAirLink.html

2. Please try the Github link below and see if you can see the video stream view.
Try https://github.com/dji-sdk/Mobile-SDK-Android first and then https://github.com/dji-sdk/Mobile-UXSDK-Android.

**Comment by idcc-cursor** [comment]
Sorry for late answers. Another problems raised --- how to use zoom with 
FPVWidgets, Z30 and Mobile SDK. Also reset camera position.

**Comment by DJI-William** [comment]
I don't think FPVWidget implements zoom features for Z30, this is a very old camera, you have to implement this feature by yourself.
setOpticalZoomFocalLength: https://developer.dji.com/api-reference/android-api/Components/Camera/DJICamera.html#djicamera_camerasettings_setopticalzoomfocallength_inline

reset: https://developer.dji.com/api-reference/android-api/Components/Gimbal/DJIGimbal.html#djigimbal_resetgimbalwithaxisandresetdirection_inline

**Comment by idcc-cursor** [comment]
Hello DJI-William
1) I have succesfully implemented Zoom in and Zoom out on C1 and C2 buttons
2) Gimbal reset does not work. I implemented the methode call on right dial push (callback works fine) but I get DJIError: "Not supported(255)"

My implementation:
    private void resetGimbal() {
        if(myGimbal != null) {
            myGimbal.reset(Axis.YAW, ResetDirection.UP_OR_DOWN, new CommonCallbacks.CompletionCallback() {
                @Override
                public void onResult(DJIError djiError) {
                    Log.i("gimbalError", djiError.toString());
                }
            });
        }
    }

**Comment by DJI-William** [comment]
What is your Z30 firmware, it must be later than v01.01.03.00. Also, if you select Axis.YAW, according to the documentation, you can only set ResetDirection.CENTER. You can check the [doc](https://developer.dji.com/api-reference/android-api/Components/Gimbal/DJIGimbal.html#djigimbal_resetdirection_inline).
