### ISSUE TITLE
ME2A Camera Mode Toggle always switches to RECORD_VIDEO

### ISSUE THREAD

**Issue by terrysmay** [dji-sdk/Mobile-UXSDK-Android#141]
Only While connected to an Mavic Enterprise 2 Advanced the Camera Mode Toggle Button at the top of the CameraControlsWidget will always select RECORD_VIDEO when initialized.  I would like it to rememeber whatever Camera Mode the user last selected.  I have tried to set the CameraKey.MODE ahead of time, but it causes the Camera Mode to toggle from SHOOT_PHOTO to RECORD_VIDEO 

What is the best way or life cycle method to set the Camera Mode. so that it will persist the users selection even if we leave the activity/fragment and come back.

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/61796'>Zendesk ticket #61796</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
A minor problem, we will look at it.

**Comment by DJI-William** [comment]
Fixed in UXSDK, it is about to release in the end of June.
